### PR TITLE
Ignore SIGPIPE for systemd

### LINKED ISSUE #13: SIGPIPE from journald prevents restart
Go does not ignore SIGPIPE for fd 1 & 2 (stdout & stderr).  
This can be a problem when programs written in Go run with systemd.

Quote from https://golang.org/pkg/os/signal/
> If the program has not called Notify to receive SIGPIPE signals, then the behavior depends on the file descriptor number. A write to a broken pipe on file descriptors 1 or 2 (standard output or standard error) will cause the program to exit with a SIGPIPE signal. A write to a broken pipe on some other file descriptor will take no action on the SIGPIPE signal, and the write will fail with an EPIPE error.

A typical systemd service configuration looks like:

```
[Service]
Type=simple
ExecStart=/path/to/go/program
Restart=on-failure
```

Services configured like this have its stdout and stderr connected with systemd-journald.
Journald is infamous for raising SIGPIPE when it restarts.  If this happens, Go programs that do not install SIGPIPE handlers will die because of the aforementioned specification.

Worse, since systemd regards it normal when programs exited with SIGPIPE because the
default value of `SuccessExitStatus` includes SIGPIPE.  As a consequence, even though the
service is configured with `Restart=on-failure`, the service will stop **cleanly** when it receives
SIGPIPE from journald.

### PR DESCRIPTION
**Pull request by ymmt2005**
Fixes #13.

### CODE REVIEW

**Comment by ymmt2005** [comment]
@nojima PTAL.

**Comment by nojima** [comment]
The following program exits with "broken pipe" when we execute `go run hoge.go | head -n3`.
This means that `signal.Ignore` does NOT ignore the SIGPIPE!!

```go
package main

import (
        "fmt"
        "os/signal"
        "syscall"
        "time"
)

func main() {
        signal.Ignore(syscall.SIGPIPE)

        for {
                fmt.Println("Hello")
                time.Sleep(time.Second)
        }
}
```

**Comment by ymmt2005** [comment]
What a fXXking behavior!

**Comment by nojima** [comment]
LGTM!!!

**Pull request merged**
